
version: 2

models:
  - name: stg_dealerships
    description: "Staged, cleaned dealership listings"
    columns:
      - name: dealership_id
        description: "Primary key"
        tests:
          - unique
          - not_null
  - name: stg_sales
    description: "Staged, cleaned sales listings"
    columns:
      - name: sale_id
        description: "Primary key"
        tests:
          - unique
          - not_null
  - name: stg_vehicle
    description: "Staged, cleaned vehicle listings"
    columns:
      - name: vehicle_id
        description: "Primary key"
        tests:
          - unique
          - not_null